spring:
  application:
    name: HomeRepOAuth

  datasource:
    url: jdbc:postgresql://82.202.143.3:5434/homerep_auth
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql:  true
    hibernate:
      ddl-auto:update
# properties:
#            hibernate:
#           format_sql: true

#sql:
#     init:
#   mode: always
#     schema-locations: "classpath:schema.sql"
#     data-locations: "classpath:data.sql"
logging:
  level:
    org:
      hibernate:
      SQL: debug
    type:
      descriptor:
        sql:
        BasicBinder: trace
#homerep:
#    app:
#        secret: 3yYVzp5nVElAYg123uRpOMq+fzQfFQ6OgoxTKuUz9Fg=
#        lifetime: 60000
server:
  address: localhost
  port: 8081
  http2:
    enabled:
      false

  tomcat:
    disable-upload-timeout: true
    keep-alive-timeout: 60000
homerep:
  secret: "yo78$$dontCrackPleaseASdujisdufasbasu"
  lifetime: 600000
  userservice: "http://82.202.143.3:8083"
  orderservice: "http://82.202.143.3:8084"

